config/routes.rb
Rails.application.routes.draw do
  
  root 'tweets#index'
  devise_for :users

  resources :tweets do
    member do
      put "like", to: "tweets#like"
      put "dislike", to: "tweets#dislike"
    end 
  end

  resources :users do
    get 'profile'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :bio, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :bio, :email, :password, :current_password)}
          end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!
    def index
        @tweets = Tweet.all
    end

    def new
        @tweet = Tweet.new
    end

    def create
        @tweet = Tweet.new(tweet_params)
        @tweet.user_id = current_user.id

        if @tweet.save
            redirect_to '/tweets#index'
        else
            render 'new'
        end
    end

    def destroy
        @tweet = Tweet.find(params[:id])
        @tweet.destroy
        redirect_to '/', :notice =>"Your Tweet Has been Deleted"
    end
    
    def like
        @tweet = Tweet.find(params[:id])
        @tweet.liked_by current_user
        redirect_to '/'
    end
      
    def dislike
        @tweet = Tweet.find(params[:id])
        @tweet.disliked_by current_user
        redirect_to '/'
    end

    private 
    def tweet_params
        params.require(:tweet).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def profile
        @userid = params[:user_id]
        @userinfo = User.find(params[:user_id])
        @usercount = @userinfo.tweets
        @tweets=Tweet.all
    end
 
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-test">
      <div>
        <span>Rails Twitter Clone</span>
        <% if user_signed_in?  %>
          Logged In as <strong><%= current_user.username%></strong>
      </div>
      <div>
          <%= link_to 'New Tweet', new_tweet_path, :class => 'btn' %> |
          <%= link_to 'My profile', user_profile_path(current_user.id), :class => 'navbar-link' %> |
          <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      </div>
      <% else %>
      </div>
      <div>
        <%= link_to 'Sign Up', new_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to 'Login', new_user_session_path, method: :delete, :class => 'navbar-link' %>
      </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="tweet-container _center">
    <div class="text-container">
          
      <%= form.label :body %>
      <br>
      <%= form.text_area :body, :id => 'body' %>
    </div>
  </div>
<div class="flex center">
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="heading">Tweets</h1>
<% @tweets.reverse.each do |tweet| %>

<div class="tweet-container _center">
    <div class="text-container"><strong class="name"><%= tweet.body %></strong>
        <div class="nickname"><%= link_to tweet.user.username, user_profile_path(tweet.user) %></div>
        <div class="nickname"><%= tweet.created_at %></div>
        
        <div class="flex">
        
          <% if current_user.liked? tweet %>
          <%= link_to dislike_tweet_path(tweet.id), method: :put do %>
            <%= image_tag("like.png", :alt => "Like", height: 18, width: 20) %>
            <%= tweet.get_likes.size %>
            <% end %>
            <% else %>
            <%= link_to like_tweet_path(tweet), method: :put do %>
                <%= image_tag("dislike.png", :alt => "Like", height: 18, width: 20) %>
                <%= tweet.get_likes.size %>
              <% end %>
          <% end %>
          
          <% if current_user == tweet.user %>
            <%= link_to "Delete", tweet_path(tweet.id), :confirm => "Are you Sure?", :method => :delete, :class => 'btn_danger' %></td>
          <% end %>
        </div>
      </div>
</div>

<% end %>

<br>

app/views/tweets/new.html.erb
<h1 class="heading">New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path, :class => 'btn_back' %>
</div>

app/views/users/profile.html.erb
<div>
<h1 class="center"><%= @userinfo.username %></h1>
<h3 class="center"><%= @userinfo.bio %></h3>
<h2 class="center">You have tweeted <%= @usercount.size %> time(s).</h2>
</div>
 
<div>
<% @tweets.reverse.each do |tweet| %>
  <% if @userinfo == tweet.user %>
  <div class="tweet-container _center">
  <div class="text-container"><strong class="name"><%= tweet.body %></strong>
      <div class="nickname"><%= link_to tweet.user.username, user_profile_path(tweet.user) %></div>
      <div class="nickname"><%= tweet.created_at %></div>
      
      <div class="flex">
      
        <% if current_user.liked? tweet %>
        <%= link_to dislike_tweet_path(tweet.id), method: :put do %>
          <%= image_tag("like.png", :alt => "Like", height: 18, width: 20) %>
          <%= tweet.get_likes.size %>
          <% end %>
          <% else %>
          <%= link_to like_tweet_path(tweet), method: :put do %>
              <%= image_tag("dislike.png", :alt => "Like", height: 18, width: 20) %>
              <%= tweet.get_likes.size %>
            <% end %>
        <% end %>
        
        <% if current_user == tweet.user %>
          <%= link_to "Delete", tweet_path(tweet.id), :confirm => "Are you Sure?", :method => :delete, :class => 'btn_danger' %></td>
        <% end %>
      </div>
    </div>
</div>
  <% end %>
<% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>